# Generated by Django 2.2.6 on 2019-10-06 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('title', models.CharField(max_length=100, null=True)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.Vacation')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('title', models.CharField(max_length=100, null=True)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.Vacation')),
            ],
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('title', models.CharField(max_length=100, null=True)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.Vacation')),
            ],
        ),
        migrations.CreateModel(
            name='Annual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacations.Vacation')),
            ],
        ),
    ]
