# Generated by Django 2.2.6 on 2019-10-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_consolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
