# Generated by Django 2.2.6 on 2019-10-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0003_vacation_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
