# Generated by Django 3.0 on 2019-12-08 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0005_auto_20191106_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_detail', models.CharField(choices=[('CON', '위로'), ('PR', '포상'), ('RE', '보상'), ('PE', '청원')], default='CON', max_length=10)),
                ('day', models.IntegerField()),
                ('title', models.CharField(max_length=100, null=True)),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='vacations.Vacation')),
            ],
        ),
        migrations.RemoveField(
            model_name='petition',
            name='vacation',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='vacation',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='vacation',
        ),
        migrations.DeleteModel(
            name='Consolation',
        ),
        migrations.DeleteModel(
            name='Petition',
        ),
        migrations.DeleteModel(
            name='Prize',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
