# Generated by Django 3.0 on 2019-12-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0006_auto_20191208_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='type_of_detail',
            field=models.CharField(choices=[('ANN', '연가'), ('CON', '위로'), ('PR', '포상'), ('RE', '보상'), ('PE', '청원')], default='ANN', max_length=10),
        ),
        migrations.DeleteModel(
            name='Annual',
        ),
    ]
