# Generated by Django 3.0 on 2019-12-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0008_auto_20191214_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='day',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
