# Generated by Django 3.0.1 on 2019-12-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0012_auto_20191221_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='user',
        ),
    ]
