# Generated by Django 3.0.1 on 2019-12-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0014_vacation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='is_used',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacation',
            name='is_gone',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
