# Generated by Django 3.0.1 on 2019-12-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0015_auto_20191221_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='is_used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
